-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a1111',
  base01 = '#140c0b',
  base02 = '#231919',
  base03 = '#534342',
  base04 = '#d8c2bf',
  base05 = '#f1dedd',
  base06 = '#382e2d',
  base07 = '#423736',

  base08 = '#ffb4ab',
  base09 = '#e2c28c',
  base0A = '#e7bdb9',
  base0B = '#ffb3ae',
  base0C = '#594319',
  base0D = '#733330',
  base0E = '#5d3f3d',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#733330',
  fg = '#1a1111',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffdea6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e2c28c',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb9',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#904a46',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#140c0b',
  fg = '#ffb3ae',
})
